### ISSUE TITLE
Unable to add file

### ISSUE THREAD

**Issue by Tuxino88** [knuxify/eartag#46]
### Describe the issue

eartag 
Traceback (most recent call last):
  File "/usr/share/eartag/eartag/file.py", line 100, in load_file
    _file = eartagfile_from_path(path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/eartag/eartag/file.py", line 44, in eartagfile_from_path
    magic_guess = magic.Magic(mime=True).from_file(path)
                  ^^^^^^^^^^^^^^^^^^^^^^
TypeError: Magic.__init__() got an unexpected keyword argument 'mime'

Build on Fedora 37 with python 3.11.0

**Comment by knuxify** [comment]
Could you check if commit a5ce1afea9dcea26e4a12bd2b195d888734330a8 fixes the issue?

Did you install python-magic from your distro's package manager (dnf/yum) or via pip? Which version is installed?

**Comment by Tuxino88** [comment]
Problems remain
Python-magic is provided in rpm by distro , version 5.42 (python3-file-magic).

**Comment by knuxify** [comment]
> Python-magic is provided in rpm by distro , version 5.42 (python3-file-magic).

That seems to be the wrong package (it *does* contain Python bindings for libmagic, but they're different from the ones used in Ear Tag).

The correct package for python-magic in Fedora would be [`python3-magic`](https://packages.fedoraproject.org/pkgs/python-magic/python3-magic/).

**Comment by Tuxino88** [comment]
> > Python-magic is provided in rpm by distro , version 5.42 (python3-file-magic).
> 
> That seems to be the wrong package (it _does_ contain Python bindings for libmagic, but they're different from the ones used in Ear Tag).
> 
> The correct package for python-magic in Fedora is [`python3-magic`](https://packages.fedoraproject.org/pkgs/python-magic/python3-magic/).

yes damn , python3-magic is cited but unavailable , solved temporarely with pip
